name: dependent-template-sync

on:
  pull_request: # run on pull requests to preview changes before applying

jobs:
  template-sync:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1 # wait for workflow_run to be successful
      - uses: ahmadnassri/action-workflow-queue@v1 # avoid conflicts, by running this template one at a time
      - uses: ahmadnassri/action-template-repository-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
